### ISSUE TITLE
Any plans to make the server components available?

### ISSUE THREAD

**Issue by dprotaso** [google/mako#1]
*first*

**Comment by timford** [comment]
Congrats on being first :)

We don’t currently have plans to open-source the server.

Our goal is to enable Google-engaged open source projects to leverage Mako to enable/accelerate sustainable performance automation. We believe that this goal can be achieved with a hosted server and a set of open source client libraries which can be used in open source tests. This will allow us to scope our support of customers with the resources that we have available for this project.

That being said, we want community feedback regarding whether this scoping and prioritization will work. If not, we are eager to hear what workflows have friction and what we can do to make engineers/teams successful.

**Comment by dprotaso** [comment]
As a Knative contributor I'd like to run these performance tests against a development branch/different cluster configurations but not spam the hosted mako dashboard. 

I think the hosted dashboard would get unwieldy if each contributor has N variations of similar perf tests.

**Comment by rakelkar** [comment]
Also using knative - can I publish results for tests run on AKS (for instance) to mako?

**Comment by timford** [comment]
> I think the hosted dashboard would get unwieldy if each contributor has N variations of similar perf tests.

Great observation. This is the reason Mako supports tags (see [TAGS.md](https://github.com/google/mako/blob/github-push-test-1/docs/TAGS.md)). You can use tags to group all your personal runs together. And the [Label Official Runs](https://github.com/google/mako/blob/github-push-test-1/docs/TAGS.md#tag-best-practices) best practice should ensure such runs don’t clutter the canonical/official charts.

For example, you might want your runs to have the tag `type=private` (to distinguish it from `type=official`), and/or `user=dprotaso`. 

Note that to enable this the test should be written in a way that makes it easy for the caller to pass in custom tags to be applied to the run. e.g.

`run_perf_test.sh --additional_tags=”type=private,user=dprotaso”`

In that example, to chart all your runs your URL could look something like: https://mako.dev/b/XXXXXXXX&tag=type%3Dprivate&tag=user%3Ddprotaso (replace ‘XXXXXXXX’ with the correct benchmark key).

With the Mako [command-line](https://github.com/google/mako/blob/github-push-test-1/docs/CLI.md), you could query for your runs like:
 
`mako list_runs --benchmark_key=”XXXXXXXX” --tag_list=”type=private,user=dprotaso”`

And in [analyzers](https://github.com/google/mako/blob/github-push-test-1/docs/ANALYZERS.md) that can make use of run history, you could populate the analyzer configuration’s RunInfoQuery (see [mako.proto](https://github.com/google/mako/blob/github-push-test-1/spec/proto/mako.proto)) with those tags in order to make sure you’re comparing apples to apples.

> Also using knative - can I publish results for tests run on AKS (for instance) to mako?

Sure. You can publish results from anywhere as long as:
* It has access to https://mako.dev
* Google authentication is established. See [AUTHENTICATION.md](https://github.com/google/mako/blob/github-push-test-1/docs/AUTHENTICATION.md). Note this section of the Google Cloud documentation about [developing code locally, deploying your application on-premises, or deploying to another public cloud](https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually).

To connect to the tags question, this is where you might add a tag like `environment=AKS`.
